services:
  backend:
    image: rockaidev/bariqe-backend:latest
    container_name: bariqe_backend
    ports:
      - "8080:8080" 
    env_file:
      - ./bariqe-dashboard/backend/.env 
    restart: always
    volumes:
      - ./bariqe-dashboard/backend/keys:/app/keys

  website:
    image: rockaidev/bariqe-website:latest
    container_name: bariqe-web
    restart: always
    env_file:
      - ./bariqe-website/.env
    ports:
      - "3005:3000"
    depends_on:
      - backend

  dashboard:
    image: rockaidev/bariqe-dashboard-frontend:latest
    container_name: bariqe_dashboard
    ports:
      - "3006:80"
    restart: always
    depends_on:
      - backend


      