name: Bariqe Dashboard Frontend CI/CD

on:
  push:
    branches: ["Dev"]
    paths:
      - 'bariqe-dashboard/frontend/**' 
      - '.github/workflows/frontend.yml'
  workflow_dispatch: 

env:
  SERVICE_NAME: bariqe-dashboard-frontend
  WORKING_DIR: ./bariqe-dashboard/frontend

jobs:
  gitleaks:
    name: Secret Detection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  dependency-check:
    name: Dependency Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm ci
        working-directory: ${{ env.WORKING_DIR }}

      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: ${{ env.SERVICE_NAME }}
          path: ${{ env.WORKING_DIR }}
          format: 'HTML' 
          out: 'dependency-reports-frontend'
          args: '--failOnCVSS 11'
      
      - name: Upload Report for Developers
        if: always() 
        uses: actions/upload-artifact@v4
        with:
          name: frontend-security-vulnerability-report
          path: dependency-reports-frontend/

  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest
    needs: [gitleaks, dependency-check]
    steps:
      - uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker image
        run: |
           docker build \
           --build-arg VITE_API_BASE_URL=${{ secrets.DASHBOARD_API_URL }} \
           -t ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }} \
           ${{ env.WORKING_DIR }}
           docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }} ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.SERVICE_NAME }}:latest
      - name: Scan Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'
          output: 'trivy-frontend-report.txt' 

      - name: Upload Trivy Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-docker-security-report
          path: trivy-frontend-report.txt

      - name: Push Image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.SERVICE_NAME }} --all-tags


  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: [build-and-push]
    steps:
    - uses: actions/checkout@v4  
    
    - name: Copy docker-compose to Server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "docker-compose.yml"
        target: "/opt/bariqe"

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /opt/bariqe
            docker compose pull dashboard
            docker compose up -d dashboard